(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects  A B C D E F G H I J K)
(:init (HANDEMPTY)(ON A G)(ONTABLE B)(ON C D)(ON D B)(ON E K)(CLEAR E)(ONTABLE F)(ONTABLE G)(ON H A)(CLEAR H)(ON I C)(ON J I)(CLEAR J)(ON K F))
(:goal (AND (HANDEMPTY)(ONTABLE A)(ON B J)(ON C I)(CLEAR C)(ONTABLE D)(CLEAR D)(ON E H)(CLEAR E)(ON F G)(CLEAR F)(ON G A)(ONTABLE H)(ON I B)(ON J K)(ONTABLE K)))
)

