(define (problem BLOCKS-4-0)
(:domain BLOCKS)
(:objects  A B C D E F G H I J K)
(:init (HANDEMPTY)(ON A C)(CLEAR A)(ON B F)(ON C G)(ONTABLE D)(ON E B)(CLEAR E)(ON F I)(ON G K)(ON H D)(CLEAR H)(ONTABLE I)(ONTABLE J)(CLEAR J)(ONTABLE K))
(:goal (AND (HANDEMPTY)(ON A J)(ON B K)(ON C E)(ONTABLE D)(CLEAR D)(ONTABLE E)(ONTABLE F)(CLEAR F)(ON G H)(ON H B)(ON I G)(CLEAR I)(ON J C)(ON K A)))
)

